name: clay_containers_plus
description: Easily create animated neumorphic container widgets for your own unique design.
version: 0.1.1+2
homepage: https://github.com/mcaubrey/clay_containers

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
